---
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Africa/Cairo
    hostname: flaresolverr
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

networks:
  default:
    external: true
    name: main
