services:
  app:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: Plex
    devices:
      - /dev/dri:/dev/dri
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Africa/UTC
      VERSION: docker
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    volumes:
      - ${HOME}/apps/plex:/config
      - "${HOME}/Media/TV Shows:/tv"
      - ${HOME}/Media/Movies:/movies

networks:
  default:
    external: true
    name: main
