---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Afirca/Cairo
    volumes:
        - ${HOME}/apps/sonarr:/config
        - ${HOME}/Media:/data
        - "/DATA/Media/TV Shows:/data/TV Shows"
    ports:
        - 8989:8989
    restart: unless-stopped

networks:
  default:
    external: true
    name: main
