services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        TZ: Africa/Cairo
        WATCHTOWER_CLEANUP: "true"
        WATCHTOWER_NOTIFICATION_URL: ntfy://ntfy.ahmedsaed.me/watchtower?title=WatchtowerUpdates
        WATCHTOWER_NOTIFICATIONS: shoutrrr
        WATCHTOWER_SCHEDULE: 0 0 20 * * SUN

networks:
  default:
    external: true
    name: main
        
