---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
    volumes:
      - ${HOME}/apps/radarr/data:/config
      - ${HOME}/Media:/data
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  default:
    external: true
    name: main
