services:
  jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
        - LOG_LEVEL=debug
        - TZ=Africa/Cairo
      hostname: jellyseerr
      ports:
            - 5055:5055
      volumes:
        - /home/ahmed/apps/jellyseerr/config:/app/config

networks:
  default:
    external: true
    name: main
