---
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${PASSWORD} #optional
      - PROXY_DOMAIN=code.ahmedsaed.me #optional
      - DEFAULT_WORKSPACE=/Documents
    volumes:
      - ${HOME}/apps/code-server/config:/config
      - ${HOME}/Documents:/Documents
    ports:
      - 8443:8443
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  default:
    external: true
    name: main
