services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
    volumes:
      - ${HOME}/apps/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  default:
    external: true
    name: main
