services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /opt/ai-apps/ollama:/root/.ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3002:8080"
    volumes:
      - /opt/ai-apps/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped

  openedai-speech:
      image: ghcr.io/matatonic/openedai-speech-min
      container_name: openedai-speech
      volumes:
        - /home/ahmed/apps/openedai/voices:/app/voices
        - /home/ahmed/apps/openedai/config:/app/config

